module coronavirus_dashboard_summary.Models.Metrics

let PostCodeMetrics =
    [|
        "newAdmissions"
        "newAdmissionsChange"
        "newAdmissionsChangePercentage"
        "newAdmissionsRollingSum"
        "newAdmissionsDirection"
        "newPeopleVaccinatedFirstDoseByPublishDate"
        "newPeopleVaccinatedSecondDoseByPublishDate"
        "cumPeopleVaccinatedFirstDoseByPublishDate"
        "cumPeopleVaccinatedSecondDoseByPublishDate"
        "cumVaccinationFirstDoseUptakeByPublishDatePercentage"
        "cumVaccinationSecondDoseUptakeByPublishDatePercentage"
        "cumVaccinationFirstDoseUptakeByVaccinationDatePercentage"
        "cumVaccinationSecondDoseUptakeByVaccinationDatePercentage"
        "cumVaccinationThirdInjectionUptakeByVaccinationDatePercentage"
        // "cumPeopleVaccinatedSpring23ByVaccinationDate75plus"
        // "cumVaccinationSpring23UptakeByVaccinationDatePercentage75plus"
        "cumPeopleVaccinatedAutumn23ByVaccinationDate65plus"
        "cumVaccinationAutumn23UptakeByVaccinationDatePercentage65plus"
        "newDeaths28DaysByDeathDate"
        "newDeaths28DaysByDeathDateChange"
        "newDeaths28DaysByDeathDateChangePercentage"
        "newDeaths28DaysByDeathDateRollingSum"
        "newDeaths28DaysByDeathDateDirection"
        "newDeaths28DaysByDeathDateRollingRate"
        "newCasesBySpecimenDateRollingSum"
        "newCasesBySpecimenDateRollingRate"
        "newCasesBySpecimenDate"
        "newCasesBySpecimenDate"
        "newCasesBySpecimenDateChange"
        "newCasesBySpecimenDateChangePercentage"
        "newCasesBySpecimenDateRollingSum"
        "newCasesBySpecimenDateDirection"
        "newVirusTests"
        "newVirusTestsChange"
        "newVirusTestsChangePercentage"
        "newVirusTestsRollingSum"
        "newVirusTestsDirection"
        "newVirusTestsBySpecimenDate"
        "newVirusTestsBySpecimenDateChange"
        "newVirusTestsBySpecimenDateChangePercentage"
        "newVirusTestsBySpecimenDateRollingSum"
        "newVirusTestsBySpecimenDateDirection"
    |]
