name: Deploy Landing Page to Sandbox Environment...

on:
 push:
  branches:
   - sandbox




jobs:
 deploy:
  runs-on: ubuntu-latest
  name: Deploy Landing Page App to Sandbox Environment
  environment: sandbox

## declares credentials for Azure Container Registry
  steps:
  - uses: actions/checkout@v2

  - name: Login to Azure Container Registry
    uses: azure/docker-login@v1
    with:
      login-server: c19dashacrprod.azurecr.io
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}
    
  - run: |
        docker build . -t c19dashacrprod.azurecr.io/landingpage-server:${{ github.sha }}-sandbox
        docker push c19dashacrprod.azurecr.io/landingpage-server:${{ github.sha }}-sandbox    

   
  - name: Deploy Container to Azure App Services
    uses: azure/webapps-deploy@v2
    with:
      app-name: 'c19dashsbuksfe01landingpage01'
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      
      images: 'c19dashacrprod.azurecr.io/landingpage-server:${{ github.sha }}-sandbox'

 test:
  runs-on: ubuntu-latest
  name: Automated Regression Tests of COVID19 Dashboard Website
  environment: sandbox
  needs: deploy

  ## calls the AIQ-Automation-Covid-Dashboard workflow to run the automated tests
  steps:
  - name: Calls the AIQ-Automation-Covid-Dashboard workflow to run the automated tests
    uses: UKHSA-Internal/AIQ-Automation-Covid-Dashboard/.github/workflows/CovidDashboard_CI.yml@Functional-Tests
    with:
        DExecution_Env: Sandbox
        DScenarioNameTest: SmokeTests_Scenario
        

      
