name: Deploy Landing Page to Sandbox Environment...

on:
 push:
  branches:
   - sandbox




jobs:
 deploy:
  runs-on: ubuntu-latest
  name: Deploy Landing Page App to Sandbox Environment
  environment: sandbox

    ## declares credentials for Azure Container Registry
  steps:
  - uses: actions/checkout@v2

  - name: Login to Azure Container Registry
    uses: azure/docker-login@v1
    with:
      login-server: c19dashacrprod.azurecr.io
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}
    
  - run: |
        docker build . -t c19dashacrprod.azurecr.io/landingpage-server:${{ github.sha }}-sandbox
        docker push c19dashacrprod.azurecr.io/landingpage-server:${{ github.sha }}-sandbox    

   
  - name: Deploy Container to Azure App Services
    uses: azure/webapps-deploy@v2
    with:
      app-name: 'c19dashsbuksfe01landingpage01'
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      
      images: 'c19dashacrprod.azurecr.io/landingpage-server:${{ github.sha }}-sandbox'

 #test:
 # name: Automated Regression Tests of COVID19 Dashboard Website
 # needs: deploy

 # ## calls the AIQ-Automation-Covid-Dashboard workflow to run the automated tests
 # uses: UKHSA-Internal/AIQ-Automation-Covid-Dashboard/.github/workflows/CovidDashboard_CI.yml@Functional-Tests
 # with:
 #   DExecution_Env: Sandbox
 #   DScenarioNameTest: SmokeTests_Scenario
        
 test:
  runs-on: ubuntu-latest
  steps:
   # ## calls the AIQ-Automation-Covid-Dashboard workflow to run the automated tests
  - name: Test
    run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }} "\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/UKHSA-Internal/AIQ-Automation-Covid-Dashboard/actions/workflows/CovidDashboard_CI.yml/dispatches \
            -d '{"ref":"Functional-Tests","inputs": { "DExecution_Env":"Sandbox", "DScenarioNameTest":"SmokeTests_Scenario" }}'


