name: Deploy Landing Page to Sandbox Environment

on:
 push:
  branches:
   - sandbox

jobs:
 deploy:
  runs-on: ubuntu-latest
  name: Deploy Landing Page App to Sandbox Environment
  environment: sandbox

## declares credentials for Azure Container Registry
  steps:
  - name: Login to Azure Container Registry
    uses: azure/docker-login@v1
    with:
      login-server: c19dashacrprod.azurecr.io
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}

   
  - name: Deploy Container to Azure App Services
    uses: azure/webapps-deploy@v2
    with:
      app-name: 'c19dashsbuksfe01landingpage01'
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      images: 'c19dashacrprod.azurecr.io/coronavirus-dashboard-summary_covid19-summary:latest'
    
      
